- code_review/work/koki-sato/PHASE1/sample.php
~インターンシップの実習 Phase1 のレビューのため~
既存のコードの変数名は可読性が低く、保守しにくいため
@koki-sato の Phase1 の実習内容
- 交通費を求めるプログラムの作成
- ホテル代を求めるプログラムの作成
- 適切な変数名/定数名を設定
> Kok sato phase1

- code_review/work/koki-sato/PHASE1/sample.php
#3 を参照
ブランチの作成を間違ったため、改めて master にマージする
> 交通費・ホテル代を計算するプログラムの修正

- YoheiHasegawa/PHASE1/sample.php
ホテル代・旅費を求める既存コードの可読性が低かったため.
変数名を説明的になり可読性が増す.
ホテル部屋代の変数名を変更
朝食代の変数名を変更
夕食代の変数名を変更
ホテル代の計算処理を記述
旅費合計の計算処理を記述
> Yohei hasegawa phase1 step2

- code_review/work/wakabayashi/PHASE1/sample.php
Aさんが就活の交通費を手入力していたので自動計算させたい
交通費の計算が楽になる
往復の学割運賃を計算
> 往復の学割運賃を計算できるようにする

- code_review/question/PHASE1/kamimura/sample.php
* このPRを出すに至った背景
* 往復の交通費が計算するため
* 現状の問題点
* 往復の交通費が計算できない
* 既存のコードの変数名がAAAなど、役割がわかりにくいものになっている
* このPRがマージされると、何がどう変わるのか？
例）
* 往復の交通費を算出することができる
* 変数名を見て役割をわかりやすくするように
* このPRで具体的に修正する箇所
* 内容
* sample.phpの運賃の計算を行っている部分
* 運賃計算部分の変数名
* 達成したい事を実現するために必要な実装項目を書く
* 特になし
> 往復の交通費を計算できるようにした

- code_review/kataoka/PHASE1/sample.php
- 往復の交通費の計算がされていない
- 変数名がAAA等でわかりづらい
- 往復の交通費の計算を行う
- コードの可読性向上
- 変数名の変更
[例]
``` php
const AAA = 12500; 
```
　　　↓
``` php
const transport_expenses = 12500; 
```
- 往復の交通費の計算の追加
``` php
$round_trip_cost = floor($one_way_fee * 2);
```
> 往復運賃を求める処理を追加&交通費等の変数名を変更

- code_review/work/doumae_kazuki/PHASE1/sample.php
学割電車運賃の計算が必要だった為
* 学割電車運賃が計算できる
* 往復料金が計算できる
*変数名がわかりやすいか
*学割電車運賃の計算が正しくできているか
*往復電車運賃の計算が正しくできているか
- [学割電車運賃の計算]
- [往復電車運賃の計算]
> 学割往復料金を計算ロジック追加

- code_review/work/kamimura/PHASE1/sample.php
* このPRを出すに至った背景
* 現状の問題点
など
* PHASE1で作成したファイルが正しい位置にない
* このPRがマージされると、何がどう変わるのか？
例）
* 正しい位置に修正される
* このPRで具体的に修正する箇所
* 内容
* ディレクトリ構造の変更
* 達成したい事を実現するために必要な実装項目を書く
* 特になし
> ファイルの位置を正しく修正

- code_review/Otuka/PHASE1/sample.php
* このPRを出すに至った背景
* 現状の問題点
* ホテル代を求めるときに必要な変数名と値が一致していない
* ホテル代を求める計算が出来ていない
* このPRがマージされると、何がどう変わるのか？
例）
* ホテル代に必要な変数名の役割が明確になる
* ホテル代を求めることができる
* このPRで具体的に修正する箇所
* 内容
* sample.phpで一日のホテル代を計算する場所
* ホテル代を求めるときに必要な変数名・定数名
* 達成したい事を実現するために必要な実装項目を書く
* [PRの承認]
> Otuka ホテル代計算をする変数名のリファクタリング

- code_review/question/PHASE1/kamimura/sample.php
- code_review/work/kamimura/PHASE1/sample.php
上村さんのインターンphase1の変更内容をmastrerに反映するため
上村さんのインターンphase1の変更内容がmastrerに反映される
work/kamimura/PHASE1の追加
> 上村さんのインターンphase1の変更内容をmastrerに反映

- code_review/work/wakabayashi/PHASE1/sample.php
Aさんは、就活費用を手入力していたため、自動化するツールを作った
宿泊費と交通費の合計金額が出力される
電車賃の往復料金を計算
ホテル部屋代と朝食、夕食の合計を計算
電車とホテルの合計金額を計算
> 電車賃に加えホテル代の計算ができるようになった

- YoheiHasegawa/PHASE2/step1/sample.php
交通費, 宿泊費, 旅費合計の計算処理が手続き的に書かれていて, 保守性・拡張性が低かったため
計算処理がクラスに分割されることで, 修正・保守性がしやすくなる
交通費の計算処理をクラス化
宿泊費の計算処理をクラス化
旅費合計の計算処理をクラス化
> YoheiHasegawa PHASE2 STEP1 交通費, 宿泊費, 旅費の計算処理をクラスに分割

- code_review/work/doumae_kazuki/PHASE1/sample.php
* 運賃含め、旅行費を計算する為
* ホテル台を計算できる
*旅行費の合計を計算できる
* 変数名が解りやすいか
* ホテル代、旅行費が正しく計算できるか
- [ホテル代の計算]
- [旅行費の計算]
> 宿泊代計算ロジック追加

- YoheiHasegawa/PHASE2/step2/HotelPlan.php
- YoheiHasegawa/PHASE2/step2/TrainPlan.php
- YoheiHasegawa/PHASE2/step2/TravelPrice.php
- YoheiHasegawa/PHASE2/step2/sample.php
クラス毎にファイルを分けられていないため, 修正がしづらいため
各クラスの修正がしやすくなる
TrainPlan Class をファイルに分割
HotelPlan Class  をファイルに分割
TravelPrice Class をファイルに分割
> YoheiHasegawa PHASE2 STEP 2 交通費計算クラス・宿泊費計算クラス・旅費合計計算クラスをファイルに分割

- YoheiHasegawa/PHASE3/step1/AirplanePlan.php
- YoheiHasegawa/PHASE3/step1/BusPlan.php
- YoheiHasegawa/PHASE3/step1/TrainPlan.php
- YoheiHasegawa/PHASE3/step1/sample.php
交通費計算クラスに電車以外の計算クラスも必要になったため
飛行機・バスの計算処理ができる
電車でグリーン車を使うことができる
AirplanePlan Class を作成
BusPlan Class を作成
TrainPlane Class を更新
> Yohei Hasegawa PHASE3 STEP1 TrainPlan Class BusPlanClass を追加 AirPlan Classを更新

- code_review/Otuka/PHASE2/step1/sample.php
プログラムの可読性を高めるため，クラス分割
* このPRを出すに至った背景
* sample.phpの行数が増えてきた
* 現状の問題点
* 手続きプログラムで可読性が低い
* このPRがマージされると、何がどう変わるのか？
例）
* 交通費を求めるクラスの作成
* ホテル代を求めるクラスの作成
* 旅費を求めるクラスの作成
* このPRで具体的に修正する箇所
* internship-contents\code_review\Otuka\PHASE2\step1\sample.php
* 内容
* TrainPlanクラスの実装
* HotelPlan
* TravelPrice
* 達成したい事を実現するために必要な実装項目を書く
> Otuka phase2 step1 交通代，ホテル代，旅費それぞれをクラスに分割

- code_review/work/Kuribayashi/PHASE1/sample.php
* 往復の移動費を計算するため
* 宿泊費用の合計費を計算するため
* 旅費費用の合計費を計算するため
* 就活の旅費が計算できる
* sample.phpを修正しました
> ホテル代を計算できるようにしました

- code_review/work/kato/PHASE2/step1/sample.php
現在のプログラムでは、全ての計算がメインクラスで行われており、どのコードが何の計算をしているのかが分かりづらい。
交通費の計算、宿泊費の計算、旅費の計算をクラスに分けて管理する。
~\internship-contents\code_review\work\kato\PHASE2\step1\sample.php
を修正する
> 旅費の合計を求める計算をクラスに分けて行う

- code_review/morikaku/phase1-1.rb
交通費を計算するプログラムで、計算を自動化したいため
交通費計算プログラム機能が追加される
クラスを使わずにプログラムが実行できる
> [WIP] 交通費を計算するプログラムを作成

- code_review/morikaku/phase1-2.rb
運賃とホテル料金の合計金額を算出したいとの意向があったため
運賃の合計金額の出力
ホテル料金の合計金額の出力
運賃とホテル料金の合計金額の出力
クラスを使わずにプログラムが実行できる
> 運賃とホテル料金の合計金額を出力するプログラムを作成

- code_review/morikaku/HotelPlan.rb
- code_review/morikaku/TrainPlan.rb
- code_review/morikaku/TravelPlan.rb
- code_review/morikaku/main.rb
- code_review/morikaku/phase2-1.rb
複数の処理をクラスとメソッドにまとめたいため
クラスを別ファイルに分割してコードを見やすくしたいため
学割を適用した往復運賃計算結果を出力する
各オプションを適用させた場合のホテル料金の計算結果を出力する
往復運賃とホテル料金を合算した旅費の合計金額を出力する
クラスとメソッドを用いて計算を実行する
往復運賃計算に必要
ホテル料金計算に必要
旅費の計算に必要
> 別ファイルに分割したクラスを使って旅費の計算を行う

- code_review/morikaku/AirplanePlan.rb
- code_review/morikaku/BusPlan.rb
- code_review/morikaku/TrainPlan.rb
- code_review/morikaku/TravelPlan.rb
- code_review/morikaku/main.rb
飛行機料金の計算機能を追加するためAirplanePlanクラスを作成
バス料金の計算機能を追加するためBusPlanクラスを作成
TrainPlanクラスへグリーン車使用の場合の運賃計算機能を追加
早割を適用した場合の飛行機料金の計算結果を出力する
クーポン割引適用した場合のバス料金の計算結果を出力する
グリーン車を使用した場合の運賃の計算結果を出力する
クラスとメソッドを用いて計算を実行する
飛行機料金計算に必要
バス料金計算に必要
TrainPlanクラスの変更
main.rbへの反映
> 飛行機料金を計算するAirplanePlanクラスとバス料金を計算するBusPlanクラスの追加、既存のTrainPlanクラス内容の変更

- code_review/morikaku/AirplanePlan.rb
- code_review/morikaku/BusPlan.rb
- code_review/morikaku/HotelPlan.rb
- code_review/morikaku/TrainPlan.rb
- code_review/morikaku/TravelPlan.rb
- code_review/morikaku/main.rb
TrainPlanクラス、AirplanePlanクラス、BusPlanクラスそれぞれで
異なる学割率で運賃計算をする必要があるため新たに学割計算メソッドを追加
任意の値で設定した学割率で運賃の計算ができる
メソッドを追加作成して計算を実行する
TrainPlanクラス
AirplanePlanクラス
BusPlanクラス
TravelPlanクラス
main.rb
> [WIP] 学割率を任意の値で計算するメソッドをTrainPlanクラス、AirplanePlanクラス、BusPlanクラスそれぞれに追加する
